// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quote.Models;

public partial class Cart
{
    public int CartDetailId { get; set; }

    public int? CartId { get; set; }

    public int? ProductId { get; set; }

    public int UserId { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}