// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quote.Models;

public partial class Contract
{
    public int ContractId { get; set; }

    public int? RequestId { get; set; }

    public string FinalPrice { get; set; }

    public string ConPrice { get; set; }

    public string ContractFile { get; set; }

    public string Status { get; set; }

    public DateTime? Date { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Request Request { get; set; }
}