// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quote.Models;

public partial class Image
{
    public int ImageId { get; set; }

    public byte[] Image1 { get; set; }

    public int? ProductId { get; set; }

    public string Description { get; set; }

    public virtual Product Product { get; set; }
}