// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quote.Models;

public partial class Notification
{
    public int NotiId { get; set; }

    public int? UserId { get; set; }

    public string Script { get; set; }

    public DateTime? Time { get; set; }
}