// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quote.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int? ContractId { get; set; }

    public string PricePay { get; set; }

    public DateTime? DatePay { get; set; }

    public string Status { get; set; }

    public string Method { get; set; }

    public int? UserId { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual User User { get; set; }
}