// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Quote.Models;

[Table("RequestDetail")]
public partial class RequestDetail
{
    [Key]
    public int RequestDetailId { get; set; }

    public int? RequestId { get; set; }

    public int? ProductId { get; set; }
}