// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quote.Models;

public partial class Request
{
    public int RequestId { get; set; }

    public bool? Status { get; set; }

    public DateTime? Date { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public int? UserId { get; set; }

    public int? ProductId { get; set; }

    public virtual Contract Contract { get; set; }

    public virtual Product Product { get; set; }

    public virtual Task Task { get; set; }

    public virtual User User { get; set; }
}