// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quote.Models;

public partial class RequestDetail
{
    public int RequestDetailId { get; set; }

    public int? RequestId { get; set; }

    public int? ProductId { get; set; }
}