// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Quote.Models;

[Table("Task")]
[Index("RequestId", Name = "UQ__Task__33A8517B52585AA5", IsUnique = true)]
public partial class Task
{
    [Key]
    public int TaskId { get; set; }

    public int? RequestId { get; set; }

    [StringLength(500)]
    public string TaskName { get; set; }

    public bool? Status { get; set; }

    [StringLength(500)]
    public string Location { get; set; }

    public int? UserId { get; set; }

    [ForeignKey("RequestId")]
    [InverseProperty("Task")]
    public virtual Request Request { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Tasks")]
    public virtual User User { get; set; }
}