// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quote.Models;

public partial class Task
{
    public int TaskId { get; set; }

    public int? RequestId { get; set; }

    public string TaskName { get; set; }

    public bool? Status { get; set; }

    public string Location { get; set; }

    public int? UserId { get; set; }

    public virtual Request Request { get; set; }

    public virtual User User { get; set; }
}